### ISSUE TITLE
librviz_cloud_annotation_com.so：对‘pcl::GlasbeyLUT::at(unsigned int)’未定义的引用

### ISSUE THREAD

**Issue by sunskyhsh** [halostorm/PCAT_open_source#1]
你好！我运行sh install.sh之后，得到了这个输出结果：
https://paste.ubuntu.com/p/VVMGjzBZsS/
好像是缺少src/rviz_cloud_annotation/lib/librviz_cloud_annotation_com.so和src/rviz_cloud_annotation/lib/librviz_cloud_annotation_plugin.so两个文件。能帮我看看怎么解决吗？

**Comment by SeanZhang777** [comment]
The catkin_make can not find the implementation of function "pcl::GlasbeyLUT::at()" in colors.cpp.
Try replacing "set(MAYBE_PCL_COMMON_COLORS "")" in **CMakeList.txt line 23** with "set(MAYBE_PCL_COMMON_COLORS "${CMAKE_CURRENT_SOURCE_DIR}/pcl_include/colors.cpp")".

**Comment by Wujielong** [comment]
ibapr-1.so.0：对‘uuid_generate@UUID_1.0’未定义的引用
collect2: error: ld returned 1 exit status

Hello! After I run sh install.sh, I get this output:

//usr/lib/x86_64-linux-gnu/libapr-1.so.0：对‘uuid_generate@UUID_1.0’未定义的引用
collect2: error: ld returned 1 exit status
rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_node.dir/build.make:476: recipe for target '/home/wujielong/PCAT_open_source/devel/lib/rviz_cloud_annotation/rviz_cloud_annotation_node' failed
make[2]: *** [/home/wujielong/PCAT_open_source/devel/lib/rviz_cloud_annotation/rviz_cloud_annotation_node] Error 1
CMakeFiles/Makefile2:1422: recipe for target 'rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_node.dir/all' failed
make[1]: *** [rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by Psyclonus2887** [comment]
This kind of problem can be caused be incomplete install of ROS, try to run `sudo apt-get install ros-kinetic-desktop-full` again and it will install packages needed.
