### ISSUE TITLE
No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so

### ISSUE THREAD

**Issue by XinPeiHou** [halostorm/PCAT_open_source#15]
[ 72%] Built target rviz_cloud_annotation_plugin_autogen
Scanning dependencies of target rviz_cloud_annotation_plugin
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by '/home/hjimi/workspace/tools/PCAT_open_source-master/devel/lib/librviz_cloud_annotation_plugin.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 75%] Building CXX object rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_plugin.dir/rviz_cloud_annotation_plugin_autogen/mocs_compilation.cpp.o
[ 78%] Building CXX object rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_plugin.dir/src/rviz_cloud_annotation_plugin.cpp.o
[ 81%] Building CXX object rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_plugin.dir/src/rviz_select_tool.cpp.o
CMakeFiles/Makefile2:704: recipe for target 'rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_plugin.dir/all' failed
make[1]: *** [rviz_cloud_annotation/CMakeFiles/rviz_cloud_annotation_plugin.dir/all] Error 2
如何解决啊

**Comment by gzchenjiajun** [comment]
@XinPeiHou 
这个问题你解决了吗？请问是如何解决的，我也遇到了

**Comment by gzchenjiajun** [comment]
@XinPeiHou 
你好，请问这个问题如何解决了，我重新做了软链接还是报同样的错误
