### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by Buerzhu** [halostorm/PCAT_open_source#2]
博主你好，我现在在使用最新版本的点云标注工具，我将点云对应的图像文件添加到～/lidar_annotation/image文件夹下，点云文件和对应的图片文件名称相同，但是在运行标注工具的时候图像显示框依旧是No image，想问一下有什么比较好的解决方法

**Comment by Aaron20127** [comment]
Hi, you can write a python file to read image from time to time.

**Comment by Qjizhi** [comment]
> Hi, you can write a python file to read image from time to time.

cloud you plz share the file?

**Comment by halostorm** [comment]
Image display is easy, it doesn't works because that I use hard code as follows... I am lazy...

https://github.com/halostorm/PCAT_open_source/blob/master/src/rviz_cloud_annotation/src/rviz_cloud_annotation_plugin.cpp#L960

**Comment by RichardHansir** [comment]
@halostorm @Buerzhu This means that I need to provide an image in ~/lidar_annotation/image corresponding to the lidar pcd file in ~/lidar_annotation/pcd?https://github.com/halostorm/PCAT_open_source/blob/master/src/rviz_cloud_annotation/src/rviz_cloud_annotation_plugin.cpp#L960

**Comment by eriche2016** [comment]
@halostorm  Hi, I am not familiar with C++, would you be kind enough to give some hints on how to display the images in the folder instead of using the hard code one. Thanks.

**Comment by eriche2016** [comment]
Hi, I have added some code to support displaying images during annotating in a cumbersome way.  It works now.

**Comment by shiqi1994** [comment]
> Hi, I have added some code to support displaying images during annotating in a cumbersome way. It works now.

Hi, may I ask how did you do the implementation?
