### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by hebeixmg** [halostorm/PCAT_open_source#5]
CMake Error at CMakeLists.txt:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake".
-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
执行sh install.sh的时候出现上面的错误，这是为啥？

**Comment by halostorm** [comment]
cmake编译出错，可能是环境原因。可以给出详细error信息
