### ISSUE TITLE
[rviz_cloud_annotation_node-2] process has died, 无法正常保存标注文件

### ISSUE THREAD

**Issue by Dongzhou-1996** [halostorm/PCAT_open_source#6]
[ INFO] [1586274937.294268862]: rviz_cloud_annotation: m_current_label 1
[ INFO] [1586274937.312954936]: rviz_cloud_annotation: ANNOTATION_TYPE 0
[ INFO] [1586274937.317525770]: rviz_cloud_annotation: shape[x1 -1.566000 x2 3.004000 y1 1.797000 y2 3.726000 z1 -1.467000 z3 -0.100000]
[ INFO] [1586274937.317583735]: BBOX[0]:0.000000 -1.566000 3.004000 0.000000 1.797000 3.726000 -1.467000 -0.100000 1.000000 -1.000000
180 Yaw 0[ INFO] [1586274937.317620274]: rviz_cloud_annotation: alpha is 0.254711
[ INFO] [1586274937.317693286]: rviz_cloud_annotation: selection set 8820 points.
[ INFO] [1586274941.427988303]: rviz_cloud_annotation: saving file: /home/dongzhou/lidar_annotation/_annotation/64line.ann
[ INFO] [1586274941.429595670]: rviz_cloud_annotation: done.
[ INFO] [1586274941.429847390]: rviz_cloud_annotation: saving cloud: /home/dongzhou/lidar_annotation/_pcd/64line.pcd
[ INFO] [1586274941.458699367]: rviz_cloud_annotation: done.
[rviz_cloud_annotation_node-2] process has died [pid 28851, exit code -11, cmd /home/dongzhou/PCAT_open_source/devel/lib/rviz_cloud_annotation/rviz_cloud_annotation_node __name:=rviz_cloud_annotation_node __log:=/home/dongzhou/.ros/log/270367da-78e8-11ea-bb0a-e82aea0b42da/rviz_cloud_annotation_node-2.log].
log file: /home/dongzhou/.ros/log/270367da-78e8-11ea-bb0a-e82aea0b42da/rviz_cloud_annotation_node-2*.log

**Comment by halostorm** [comment]
2020-04-02 commit 关闭了默认的16线地面检测，地面id未初始化，已更新。
