### ISSUE TITLE
 The plugin for class 'rviz_cloud_annotation/Annotation Tool' failed to load.  Error: Failed to load library 

### ISSUE THREAD

**Issue by zyxcambridge** [halostorm/PCAT_open_source#7]
[ERROR] [1589107141.546822435]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation Tool' failed to load.  Error: Failed to load library /share_zyx/PCAT_open_source/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /share_zyx/PCAT_open_source/devel/lib//librviz_cloud_annotation_plugin.so))
[ERROR] [1589107141.556759737]: PluginlibFactory: The plugin for class 'rviz_cloud_annotation/Annotation' failed to load.  Error: Failed to load library /share_zyx/PCAT_open_source/devel/lib//librviz_cloud_annotation_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /share_zyx/PCAT_open_source/devel/lib//librviz_cloud_annotation_plugin.so))
================================================================================REQUIRED process [annotation_rviz-2] has died!
process has finished cleanly
log file: /root/.ros/log/7c1fa32e-92a5-11ea-9bf1-e0d55ef88a30/annotation_rviz-2*.log
Initiating shutdown!

**Comment by halostorm** [comment]
cmake doesn't link Qt5 dll (.so) rightly, maybe you do not install ros rightly, which contains qt5 ?  Or maybe your qt5 conficts with other qt version.
