### ISSUE TITLE
some confusions about Bbox label definition

### ISSUE THREAD

**Issue by Dongzhou-1996** [halostorm/PCAT_open_source#8]
![image](https://user-images.githubusercontent.com/20870192/81584066-d561bb80-93e4-11ea-8804-021ca95900f0.png)
According to the definition of bbox label u provided in 'image/s5.png', the object of interest can be described by its size (length, width, height), location (x_c, y_c, z_c), theta and alpha. However, I have three question about the definition of bbox label:
1. which object point does the location (x_c, y_c, z_c) represents? the center of target or just like KITTI dataset (the bottom center of target)? And is the location (x_c, y_c, z_c) the original of object coordinate system?

2. the 3D size of object includes length, width and height, Which axis of object coordinate system are they respectively aligned with?  length-x, width-y, height-z?

3. how is the alpha defined? the angle between the x-axis of observer coordinates and the x-axis of object coordinates? which case is it defined as positive？and when is negative?

regards,
dong zhou

根据你们在 'image/s5.png' 所提供的bbox label定义来看，感兴趣目标能够由 size (length, width, height), location (x_c, y_c, z_c), theta and alpha 来描述。 但是我对bbox label定义有几个问题没有弄明白：
1. label中的the location (x_c, y_c, z_c) 对应目标的哪个点？目标中心或者像KITTI数据集那样，对应目标底面中心？还有the location (x_c, y_c, z_c) 应该就是目标坐标系的原点吧？

2. 目标三维尺寸包括长、宽、高，它们分别对应目标坐标系的哪个轴？长对应x轴，宽对应y轴，高对应z轴？

3. alpha角是如何定义的？它是观测坐标系x轴和目标坐标系x轴的夹角吗？这个alpha角什么时候为正，什么时候为负？

非常期待您的回答！
周栋

**Comment by halostorm** [comment]
1. label中的the location (x_c, y_c, z_c) 对应目标的哪个点？目标中心或者像KITTI数据集那样，对应目标底面中心？还有the location (x_c, y_c, z_c) 应该就是目标坐标系的原点吧？
 参考系是采集车车体系，(x_c, y_c, z_c) 是3Dbbox中心
2. 目标三维尺寸包括长、宽、高，它们分别对应目标坐标系的哪个轴？长对应x轴，宽对应y轴，高对应z轴？
对的。
3. alpha角是如何定义的？它是观测坐标系x轴和目标坐标系x轴的夹角吗？这个alpha角什么时候为正，什么时候为负？
x轴夹角，符号定义，正->逆时针

**Comment by russellyq** [comment]
@halostorm 
你好，请问 theta角是顺时针为正吗

**Comment by halostorm** [comment]
右手坐标系，逆时针





------------------ Original ------------------
From: russellyq ***@***.***&gt;
Date: Tue,Jan 18,2022 2:13 PM
To: halostorm/PCAT_open_source ***@***.***&gt;
Cc: halo ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [halostorm/PCAT_open_source] some confusions about Bbox labeldefinition (#8)





 
@halostorm
 你好，请问 theta角是顺时针为正吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
